### ISSUE TITLE
使用scoop search和scoop install ContextMenuManager报错

### ISSUE THREAD

**Issue by DoveBoy** [LuoHuiRu/ScoopBucket#1]
![image](https://user-images.githubusercontent.com/19201447/123093619-7c28e000-d45e-11eb-9e3f-f50ace08e1da.png)
![image](https://user-images.githubusercontent.com/19201447/123093669-89de6580-d45e-11eb-8af7-14e5be770e04.png)

**Comment by LuoHuiRu** [comment]
我这安装是正常的，是否是你那scoop配置问题

**Comment by DoveBoy** [comment]
[scoop search error ](https://github.com/lukesampson/scoop/issues/4394#issuecomment-869071576)这边官方说是仓库有问题

**Comment by LuoHuiRu** [comment]
我这边是正常的呢，你把原先的bucket删除，重新导入试试呢 @DoveBoy
